---
# Global Linux baseline

system_timezone: America/Los_Angeles

common_packages:
  - ca-certificates
  - curl
  - wget
  - git
  - vim
  - nano
  - unzip
  - zip
  - rsync
  - jq
  - tree
  - tmux
  - htop
  - btop
  - lsof
  - net-tools
  - dnsutils
  - bash-completion

enable_system_updates: true
