---
all:
  vars:
    ansible_user: linuxadmin
    ansible_ssh_private_key_file: /home/linuxadmin/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:

    webservers:
      hosts:
        web1.networkbughie.net:
          ansible_host: 10.10.0.248
          http_port: 80

        web2.networkbughie.net:
          ansible_host: 10.10.0.244
          http_port: 8080

      vars:
        nginx_worker_processes: 4

    appservers:
      hosts:
        appserver:
          ansible_host: 10.10.0.250

        appserver-02:
          ansible_host: 10.10.0.175  

    dbservers:
      hosts:
        db-primary:
          ansible_host: 10.10.0.244
          mysql_role: primary

        db-replica:
          ansible_host: 10.10.0.248
          mysql_role: replica

      vars:
        mysql_port: 3306

    staging:
      hosts:
        staging-server:
          ansible_host: 10.10.0.244

      vars:
        deployment_environment: staging

    production:
      children:
        webservers:
        dbservers:

      vars:
        deployment_environment: production
        monitoring_enabled: true
