# Ungrouped host
10.10.0.246

[webservers]
10.10.0.244 
10.10.0.248 

[appservers]
10.10.0.250 

[dbservers]
db1.networkbughie.net ansible_host=10.10.0.244
db2.networkbughie.net ansible_host=10.10.0.248

[appservers]
app1.networkbughie.net ansible_port=2222
app2.networkbughie.net ansible_port=2222

[production:children]
webservers
dbservers
appservers

[production:vars]
ansible_user=linuxadmin
ansible_ssh_private_key_file=~/.ssh/ansible_key
deployment_environment=production
