all:
  vars:
    ansible_user: linuxadmin
    ansible_ssh_private_key_file: /home/linuxadmin/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    webservers:
      hosts:
        web1.networkbughie.net:
          ansible_host: 10.100.101.198
          ansible_hostname: appserver-03
          http_port: 80

        web2:
          ansible_host: 10.10.0.22
          ansible_hostname: proxubun3
          http_port: 8080

      vars:
        nginx_worker_processes: 4

    appservers:
      hosts:
        appserver:
          ansible_host: 10.10.0.52
          ansible_hostname: appserver

        appserver-02:
          ansible_host: 10.10.0.218
          ansible_hostname: proxserver1

        appserver-3:
          ansible_host: 10.100.101.198
          ansible_hostname: docker-srv

        appserver-04:
          ansible_host: 10.10.0.6
          ansible_hostname: proxubun4

    dbservers:
      hosts:
        db-primary:
          ansible_host: 10.100.100.228
          ansible_hostname: webserver
          mysql_role: primary

        db-replica:
          ansible_host: 10.100.100.94
          ansible_hostname: ubuntu-ser-vm1
          mysql_role: replica

      vars:
        mysql_port: 3306

    staging:
      hosts:
        staging-server:
          ansible_host: 10.100.101.70
          ansible_hostname: ansible-srv

      vars:
        deployment_environment: staging

    production:
      children:
        webservers:
        dbservers:

      vars:
        deployment_environment: production
        monitoring_enabled: true

